/*
 * This source file was generated by the Gradle 'init' task
 */
package yamato;

import java.io.BufferedReader;
import java.io.InputStreamReader;

import main.java.yamato.standarization.standarization;

public class App {
    
    private static int FILE_TYPE_NORMAL = 1;
    private static int FILE_TYPE_REVERSE = 2;

    public static void main(String[] args) {

        int fileType = 0;
        if(args.length > 0) {
            // 標準入力を読み取る
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

            String line = null;
            while (br.readLine() != null) {
                line = br.readLine();
                // コロンが一箇所でも見つかる場合、正規化前のファイルと判定
                if(line.indexOf(":") != -1){
                    fileType = FILE_TYPE_NORMAL; // 通常の正規化へ
                    break;
                }
                fileType = FILE_TYPE_REVERSE; // 逆変換へ
            }
            br.close();

            // 標準入力のTSVデータのパターンに応じて正規化への変換、逆変換に分岐
            BufferedReader tsvData = new BufferedReader(new InputStreamReader(System.in));
            if(fileType == FILE_TYPE_NORMAL){
                standarization.standardizeTSV(tsvData);    
            }else if(fileType == FILE_TYPE_REVERSE){
                standarization.revrerseStandardizeTSV(tsvData);
            }
        }else{
            System.out.println("tsvデータを渡してください");
        }
    }
}
